#pragma once
#include "vehicles.hpp"
#include <types.hpp>

const StaticArray<VehicleComponentSlot, MAX_VEHICLE_COMPONENTS> allComponentSlots = {
    VehicleComponent_Spoiler,
    VehicleComponent_Spoiler,
    VehicleComponent_Spoiler,
    VehicleComponent_Spoiler,
    VehicleComponent_Hood,
    VehicleComponent_Hood,
    VehicleComponent_Roof,
    VehicleComponent_SideSkirt,
    VehicleComponent_Nitro,
    VehicleComponent_Nitro,
    VehicleComponent_Nitro,
    VehicleComponent_Hood,
    VehicleComponent_Hood,
    VehicleComponent_Lamps,
    VehicleComponent_Spoiler,
    VehicleComponent_Spoiler,
    VehicleComponent_Spoiler,
    VehicleComponent_SideSkirt,
    VehicleComponent_Exhaust,
    VehicleComponent_Exhaust,
    VehicleComponent_Exhaust,
    VehicleComponent_Exhaust,
    VehicleComponent_Exhaust,
    VehicleComponent_Spoiler,
    VehicleComponent_Lamps,
    VehicleComponent_Wheels,
    VehicleComponent_SideSkirt,
    VehicleComponent_SideSkirt,
    VehicleComponent_Exhaust,
    VehicleComponent_Exhaust,
    VehicleComponent_SideSkirt,
    VehicleComponent_SideSkirt,
    VehicleComponent_Roof,
    VehicleComponent_Roof,
    VehicleComponent_Exhaust,
    VehicleComponent_Roof,
    VehicleComponent_SideSkirt,
    VehicleComponent_Exhaust,
    VehicleComponent_Roof,
    VehicleComponent_SideSkirt,
    VehicleComponent_SideSkirt,
    VehicleComponent_SideSkirt,
    VehicleComponent_SideSkirt,
    VehicleComponent_Exhaust,
    VehicleComponent_Exhaust,
    VehicleComponent_Exhaust,
    VehicleComponent_Exhaust,
    VehicleComponent_SideSkirt,
    VehicleComponent_SideSkirt,
    VehicleComponent_Spoiler,
    VehicleComponent_Spoiler,
    VehicleComponent_SideSkirt,
    VehicleComponent_SideSkirt,
    VehicleComponent_Roof,
    VehicleComponent_Roof,
    VehicleComponent_Roof,
    VehicleComponent_SideSkirt,
    VehicleComponent_SideSkirt,
    VehicleComponent_Spoiler,
    VehicleComponent_Exhaust,
    VehicleComponent_Spoiler,
    VehicleComponent_Roof,
    VehicleComponent_SideSkirt,
    VehicleComponent_SideSkirt,
    VehicleComponent_Exhaust,
    VehicleComponent_Exhaust,
    VehicleComponent_Exhaust,
    VehicleComponent_Roof,
    VehicleComponent_Roof,
    VehicleComponent_SideSkirt,
    VehicleComponent_SideSkirt,
    VehicleComponent_SideSkirt,
    VehicleComponent_SideSkirt,
    VehicleComponent_Wheels,
    VehicleComponent_Wheels,
    VehicleComponent_Wheels,
    VehicleComponent_Wheels,
    VehicleComponent_Wheels,
    VehicleComponent_Wheels,
    VehicleComponent_Wheels,
    VehicleComponent_Wheels,
    VehicleComponent_Wheels,
    VehicleComponent_Wheels,
    VehicleComponent_Wheels,
    VehicleComponent_Wheels,
    VehicleComponent_Wheels,
    VehicleComponent_Stereo,
    VehicleComponent_Hydraulics,
    VehicleComponent_Roof,
    VehicleComponent_Exhaust,
    VehicleComponent_SideSkirt,
    VehicleComponent_Roof,
    VehicleComponent_Exhaust,
    VehicleComponent_SideSkirt,
    VehicleComponent_SideSkirt,
    VehicleComponent_SideSkirt,
    VehicleComponent_Wheels,
    VehicleComponent_Wheels,
    VehicleComponent_Wheels,
    VehicleComponent_SideSkirt,
    VehicleComponent_FrontBumper,
    VehicleComponent_SideSkirt,
    VehicleComponent_SideSkirt,
    VehicleComponent_Roof,
    VehicleComponent_Exhaust,
    VehicleComponent_Exhaust,
    VehicleComponent_SideSkirt,
    VehicleComponent_SideSkirt,
    VehicleComponent_SideSkirt,
    VehicleComponent_FrontBumper,
    VehicleComponent_FrontBumper,
    VehicleComponent_FrontBumper,
    VehicleComponent_FrontBumper,
    VehicleComponent_Exhaust,
    VehicleComponent_Exhaust,
    VehicleComponent_FrontBumper,
    VehicleComponent_FrontBumper,
    VehicleComponent_FrontBumper,
    VehicleComponent_SideSkirt,
    VehicleComponent_SideSkirt,
    VehicleComponent_SideSkirt,
    VehicleComponent_SideSkirt,
    VehicleComponent_SideSkirt,
    VehicleComponent_FrontBumper,
    VehicleComponent_SideSkirt,
    VehicleComponent_FrontBumper,
    VehicleComponent_Exhaust,
    VehicleComponent_Exhaust,
    VehicleComponent_Roof,
    VehicleComponent_Exhaust,
    VehicleComponent_Roof,
    VehicleComponent_Roof,
    VehicleComponent_Exhaust,
    VehicleComponent_SideSkirt,
    VehicleComponent_SideSkirt,
    VehicleComponent_Exhaust,
    VehicleComponent_Exhaust,
    VehicleComponent_SideSkirt,
    VehicleComponent_Spoiler,
    VehicleComponent_Spoiler,
    VehicleComponent_RearBumper,
    VehicleComponent_RearBumper,
    VehicleComponent_VentLeft,
    VehicleComponent_VentRight,
    VehicleComponent_VentLeft,
    VehicleComponent_VentRight,
    VehicleComponent_Spoiler,
    VehicleComponent_Spoiler,
    VehicleComponent_RearBumper,
    VehicleComponent_RearBumper,
    VehicleComponent_RearBumper,
    VehicleComponent_RearBumper,
    VehicleComponent_FrontBumper,
    VehicleComponent_FrontBumper,
    VehicleComponent_RearBumper,
    VehicleComponent_FrontBumper,
    VehicleComponent_RearBumper,
    VehicleComponent_FrontBumper,
    VehicleComponent_Spoiler,
    VehicleComponent_RearBumper,
    VehicleComponent_FrontBumper,
    VehicleComponent_RearBumper,
    VehicleComponent_Spoiler,
    VehicleComponent_Spoiler,
    VehicleComponent_Spoiler,
    VehicleComponent_FrontBumper,
    VehicleComponent_FrontBumper,
    VehicleComponent_RearBumper,
    VehicleComponent_RearBumper,
    VehicleComponent_FrontBumper,
    VehicleComponent_FrontBumper,
    VehicleComponent_FrontBumper,
    VehicleComponent_FrontBumper,
    VehicleComponent_FrontBumper,
    VehicleComponent_FrontBumper,
    VehicleComponent_FrontBumper,
    VehicleComponent_RearBumper,
    VehicleComponent_RearBumper,
    VehicleComponent_RearBumper,
    VehicleComponent_FrontBumper,
    VehicleComponent_RearBumper,
    VehicleComponent_FrontBumper,
    VehicleComponent_FrontBumper,
    VehicleComponent_RearBumper,
    VehicleComponent_RearBumper,
    VehicleComponent_FrontBumper,
    VehicleComponent_RearBumper,
    VehicleComponent_RearBumper,
    VehicleComponent_FrontBumper,
    VehicleComponent_FrontBumper,
    VehicleComponent_FrontBumper,
    VehicleComponent_FrontBumper,
    VehicleComponent_RearBumper,
    VehicleComponent_RearBumper
};

const StaticArray<uint8_t, MAX_VEHICLE_COMPONENTS> componentValidVehicleModel = {
    0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF,
    0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF,
    0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xA0, 0xA0, 0xA0, 0xA0,
    0xA0, 0xA0, 0xA0, 0xA0, 0xA2, 0xA2, 0xA2, 0xA2, 0xA2, 0xA2,
    0xA2, 0xA2, 0xAF, 0xAF, 0xAF, 0xA5, 0xA5, 0xA5, 0xA5, 0xA5,
    0xA5, 0xA5, 0xA5, 0xA5, 0xA5, 0xA1, 0xA1, 0xA1, 0xA1, 0xA1,
    0xA1, 0xA1, 0xA1, 0xA1, 0xA1, 0x9F, 0x9F, 0x9F, 0x9F, 0x9F,
    0x9F, 0x9F, 0x9F, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF,
    0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0x9E, 0x9E,
    0x9E, 0x9E, 0x9E, 0x9E, 0x9E, 0x9E, 0xFF, 0xFF, 0xFF, 0xAF,
    0x86, 0x86, 0xA7, 0x88, 0x88, 0x88, 0x86, 0x88, 0x88, 0x87,
    0x87, 0x87, 0x87, 0x87, 0x87, 0x87, 0x87, 0x87, 0x87, 0x87,
    0x87, 0x87, 0x86, 0x86, 0x86, 0x86, 0x86, 0x86, 0x88, 0xA7,
    0xA7, 0xA7, 0xA7, 0xA7, 0xB0, 0xB0, 0xB0, 0xB0, 0xA0, 0xA0,
    0xA0, 0xA0, 0xFF, 0xFF, 0xFF, 0xFF, 0xA2, 0xA2, 0xA2, 0xA2,
    0xA5, 0xA5, 0xA5, 0xA5, 0xA1, 0xA1, 0xA1, 0xA1, 0x9F, 0x9F,
    0x9F, 0x9F, 0x9F, 0x9E, 0x9E, 0x9E, 0x9E, 0x9E, 0x9E, 0xA0,
    0xA0, 0xA2, 0xA2, 0x9F, 0xAF, 0xAF, 0xAF, 0xAF, 0x86, 0x86,
    0x86, 0x88, 0x88, 0x88, 0x88, 0x86, 0xA7, 0xA7, 0xA7, 0xA7,
    0xB0, 0xB0, 0xB0, 0xB0
};

static bool isValidComponentForVehicleModel(int vehicleModel, int componentId)
{
    componentId -= 1000;
    if (0 > componentId || componentId > MAX_VEHICLE_COMPONENTS) {
        return false;
    }
    auto componentModel = componentValidVehicleModel[componentId];
    return componentModel == 0xFF || componentModel == vehicleModel - 400;
}

static int getVehicleComponentSlot(int component)
{
    component -= 1000;
    if (0 <= component && component < MAX_VEHICLE_COMPONENTS) {
        return allComponentSlots[component];
    }
    return VehicleComponent_None;
};
